[package]
name = "ant_upload"
version = "0.1.0"
edition = "2024"

[dependencies]
# autonomi = "0.4.4"
autonomi = { path = "autonomi/autonomi" }
eframe = "0.24.0"
egui = "0.24.0"
image = "0.25.6"
tokio = { version = "1.39.0", features = ["full"] }
