name: Release on Main Commit

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  linux-release:
    if: contains(github.event.head_commit.message, '[release]')
    name: Build Linux targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev
          rustup target add ${{ matrix.target }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          cargo install cross

      - name: Clone autonomi dependency
        run: |
          git clone https://github.com/maidsafe/autonomi.git
          cd autonomi
          git fetch origin client-light-networking
          git checkout client-light-networking
          cd ..

      - name: Build x86_64
        uses: actions-rs/cargo@v1
        if: matrix.target == 'x86_64-unknown-linux-musl'
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Build ARM
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ant_upload

  macos-release:
    if: contains(github.event.head_commit.message, '[release]')
    name: Build MacOS targets
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Clone autonomi dependency
        run: |
          git clone https://github.com/maidsafe/autonomi.git
          cd autonomi
          git fetch origin client-light-networking
          git checkout client-light-networking
          cd ..

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/ant_upload

  create-release:
    name: Create Release
    needs: [linux-release, macos-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Generate release tag
        id: tag
        run: |
          echo "tag_name=$(date +'v%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "release_name=Release $(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: ${{ steps.tag.outputs.release_name }}
          body: |
            Automated release from main branch
            
            Built targets:
            - Linux (x86_64, aarch64)
            - MacOS (x86_64, aarch64)
          draft: false
          prerelease: false
          files: |
            x86_64-unknown-linux-musl/ant_upload
            aarch64-unknown-linux-musl/ant_upload
            x86_64-apple-darwin/ant_upload
            aarch64-apple-darwin/ant_upload
